version: "3.9"

services:
  auth-frontend:
    container_name: auth-nginx
    image: "nginx:1.21"
    restart: unless-stopped
    ports: 
      - 8055:80
    volumes:
      - ./frontend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/web/:/usr/share/nginx/html/:ro
  auth-backend:
    container_name: auth-backend
    build:
      context: .
    restart: unless-stopped
    environment:
      - SECRET_KEY=c5d4e33ec97e130f6d473694d508748a7f37dd4bcc8f81b1af9bd2146321a147
      - ALGORITHM=HS512
      - ACCESS_TOKEN_EXPIRE_MINUTES=43200
      - PASSWORD=letmein
      - EXPOSE_METRICS=true
      - LOGOUT_REDIRECT="/"
